name: Custom React S2I Action
description: Source-to-Image (S2I) style action that builds and pushes React app to GHCR

inputs:
  registry:
    required: true
  username:
    required: true
  password:
    required: true
  image-name:
    required: true
  tag:
    required: false
    default: latest

outputs:
  image-name:
    description: Full image name with SHA tag
  image_digest:
    description: Docker image digest
  push_status:
    description: Push status

runs:
  using: composite
  steps:
    - name: Make entrypoint executable
      run: chmod +x ${{ github.action_path }}/entrypoint.sh
      shell: bash

    - name: Build & Push React Image
      shell: bash
      env:
        INPUT_REGISTRY: ${{ inputs.registry }}
        INPUT_USERNAME: ${{ inputs.username }}
        INPUT_PASSWORD: ${{ inputs.password }}
        INPUT_IMAGE_NAME: ${{ inputs.image-name }}
        INPUT_TAG: ${{ inputs.tag }}
      run: ${{ github.action_path }}/entrypoint.sh
