name: Custom React S2I Action
description:  Source-to-Image (S2I) style action that builds and pushes React app to GHCR

inputs:
    registry:
        description: Container registry(ex. ghcr.io)
        required: true
    username:
        description: Registry username
        required: true
    password:
        description: Registry password/token
        required: true
    image-name:
        description: Image name without tag
        required: true
    tag:
        description: Image tag 
        default: latest
        required: false
        
outputs:
  image_name:
    description:  Full image name with SHA tag
  image_digest:
    description:  Docker image digest
  push_status:
    description:  Push status (success/failed)

runs:
  using: composite
  steps:
    - name: Make entrypoint executable
      run: chmod +x ${{ github.action_path }}/entrypoint.sh
      shell: bash

    - name: Build & Push React Image
      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash