FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY dist/ /usr/share/nginx/html/
#COPY nginx.conf /etc/nginx/conf.d/default.conf
RUN apk add --no-cache wget && \
    wget -O /etc/nginx/conf.d/default.conf https://raw.githubusercontent.com/nadametwaly/DevOps-Practical-Project-CI-CD-with-Multi-Environment-Deployment/main/nginx.conf && \
    apk del wget
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
